INSTALL_PATH=${HOME}/.local/bin
EXECUTABLE=templ
EXECUTABLE_PATH=${INSTALL_PATH}/${EXECUTABLE}

install:
	cp templ.py ${EXECUTABLE_PATH}
	chmod +x ${EXECUTABLE_PATH}

uninstall:
	rm ${EXECUTABLE_PATH}

